--- 
  - name: Install RabbitMQ broker, PostgreSQL and needed dependencies
    tags: installall
    shell: apt-get -y install "{{item}}"
    with_items:
      - rabbitmq-server
      - postgresql
      - postgresql-client
      - python-psycopg2
      - libpq-dev
      - curl
      - python-dev
      - git

  - name: Install Celery, Django and Django rest framework
    tags: celerydjangoinstall
    pip: "name={{item.name}}"
    with_items:
      - { name: 'celery' }
      - { name: 'Django' }
      - { name: 'djangorestframework==2.4.3' }
      - { name: 'markdown' }
      - { name: 'django-filter' }
      - { name: 'nose' }
      - { name: 'mock' }
      - { name: 'rest_framework_ember' }
      - { name: 'djorm-pgarray' }
      - { name: 'paramiko' }
      - { name: 'kamaki==0.13rc3'}
      - { name: 'ansible==1.7.2' }

  - name: Copy script celeryd for daemonic workers
    tags: celerydcopy
    copy: src=celeryd dest=/etc/init.d/celeryd owner=root mode=0744
    when: is_daemon

  - name: Copy celeryd configuration
    tags: celerydconfcopy
    template: src=celeryd_conf.j2 dest=/etc/default/celeryd owner=root
    when: is_daemon

  - name: Copy script celerybeat for daemonic periodic tasks
    tags: celerybeatcopy
    copy: src=celerybeat dest=/etc/init.d/celerybeat owner=root mode=0744
    when: is_periodic_task

  - name: Copy celerybeat configuration
    tags: celerybeatconfcopy
    template: src=celerybeat_conf.j2 dest=/etc/default/celerybeat owner=root
    when: is_periodic_task

  - name: create directory for projects
    tags: createprojectdirectory
    command: mkdir {{myprojectdir}} creates={{myprojectdir}}

  - name: Git clone e-science project in the git directory
    tags: gitcloneproject
    command: git clone -b develop {{escience_repo}} {{myprojectname}} chdir={{myprojectdir}}

  - name: Copy package.json to webserver
    tags: cppackagejson
    copy: src=package.json dest={{myprojectdir}}/{{myprojectname}} owner=orca_admin mode=0644

  - name: Copy Gruntfile.j2 template to webserver
    tags: cpgruntfile
    template: src=Gruntfile.j2 dest={{myprojectdir}}/{{myprojectname}} owner=orca_admin mode=0644

  - name: Rename Gruntfile.j2 template to Gruntfile.js
    tags: renamegruntfile
    command: mv Gruntfile.j2 Gruntfile.js chdir={{myprojectdir}}/{{myprojectname}}
    
  - name: Download NVM
    tags: download_nvm
    shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.12.1/install.sh | bash

  - name: NMV Commands in Terminal
    tags: nvm_commands
    shell: cd;bash -lc "source ~/.profile" 

  - name: Install NVM
    tags: nvm_install
    shell: cd;bash -lc "nvm install v0.11.13"

  - name: NVM default version
    tags: nvm_default
    shell: cd;bash -lc "nvm alias default v0.11.13"

  - name: Install grunt-cli
    tags: grunt-cli_install
    shell: cd;bash -lc "npm install -g grunt-cli"
   
  - name: Install and add Grunt
    tags: grunt_install_add
    shell: cd;bash -lc "npm install grunt --save-dev"

  - name: Link npm
    tags: npm_link
    shell: cd {{project_path}};bash -lc "npm link"
    
  - name: Install and add uglify
    tags: uglify_install_add
    shell: cd {{project_path}};bash -lc "npm install grunt-contrib-uglify --save-dev"

  - name: Install and add removelogging
    tags: removelogging_install_add
    shell: cd {{project_path}};bash -lc "npm install grunt-remove-logging"
    
  - name: Run grunt tasks (uglify, removelogging)
    tags: grunt_tasks_run
    shell: cd {{project_path}}; bash -lc "grunt default"

  - name: Edit pg_hba.conf
    lineinfile: line="local\tall\t\tpostgres\t\t\t\ttrust" dest=/etc/postgresql/9.1/main/pg_hba.conf state=present regexp="local(\s)+all(\s)+postgres(\s)+(?=peer)" backrefs=yes
    tags: pghbaconf_to_trust
 
  - name: Restart PostgreSql service
    service: name=postgresql state=restarted
    tags: postgresrestart

  - name: Create PostgreSql user
    postgresql_user: name={{db_user}} password={{db_password}} role_attr_flags=CREATEDB,NOSUPERUSER,NOCREATEROLE
    tags: createpostgresuser

  - name: Create PostgreSql database
    postgresql_db: name={{db_name}} owner={{db_user}}
    tags: createpostgresdb

  - name: copy Django settings.py template
    template: src=settings.j2 dest=/etc/
    tags: djangosettingscopy
    
  - name: Edit Django project settings.py
    shell: sed -i '/# Database/,$d' settings.py chdir={{settings_path}}
    tags: editsettings

  - name: Append settings template
    shell: cat /etc/settings.j2 >> {{settings_path}}/settings.py
    tags: appendsettings

  - name: Django project migrate
    shell: python manage.py migrate chdir={{myprojectdir}}/{{myprojectname}}/{{ember_django_dir}}
    tags: djangomigrate

  - name: Revert pg_hba.conf to default
    lineinfile: line="local\tall\t\tpostgres\t\t\t\tpeer" dest=/etc/postgresql/9.1/main/pg_hba.conf state=present regexp="local(\s)+all(\s)+postgres(\s)+(?=trust)" backrefs=yes
    tags: pghbaconf_to_peer
 
  - name: Restart PostgreSql service
    service: name=postgresql state=restarted
    tags: postgresrestart
   
  - name: Create Django superuser
    shell: echo "from django.contrib.auth.models import User; User.objects.create_superuser('{{django_admin_name}}', '{{django_admin_email}}', '{{django_admin_password}}')" | python manage.py shell chdir={{myprojectdir}}/{{myprojectname}}/{{ember_django_dir}}
    tags: djangosuperuser
    
  - name: Change owner of projects
    command: chown -R orca_admin:orcagroup {{myprojectdir}}
    tags: chownorca

  - name: Django runserver
    command: python manage.py runserver 0.0.0.0:{{django_port}} chdir={{myprojectdir}}/{{myprojectname}}/{{ember_django_dir}}
    tags: runserver
