language: python
python:
- '2.7'
env:
  global:
  - secure: YELLNiIaLsnIch5DFHgKk9ZFlWasujveMGc8qkIFrct1bis///wa0oa1BB8KGgPv4KWy8KUaBNZEv8L+DTRjHr2km1T5zf/G3OERQlrFrTqyunBaYazllDQTmqB7P+oDx3b4lTrHuD1vmdns9fJHqQaEnshA4VKSs5biox3avww=
  - secure: YDlXPTeVg3s8/TzbQ8YPyo5Rv9XGqgFPMJyWNJb6Vn6JdncMwiV5VJ9hbiTQC2VQ16CFDqPx174RX5WNYzEr/IvALSDO1KVzODlduQ9tL2xUwR/yGMDeCKgfPAPSf2WzzGY9Szh/nmTetpApp/jJnrzF7wQajOuHpAW86Op9PY4=
install:
- pip install kamaki==0.13rc3
- pip install paramiko
- pip install ansible
- pip install django
- pip install selenium
- pip install mock
- pip install rednose
- pip install nose-cov
- sudo apt-get install sshpass
script: nosetests -sv tests/test_create_bare_cluster.py
before_install:
- openssl aes-256-cbc -K $encrypted_1e993d61b648_key -iv $encrypted_1e993d61b648_iv
  -in .config.txt.enc -out .private/.config.txt -d
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- nohup bash -c "webdriver-manager start 2>&1 &"
