language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install kamaki"
  - "pip install paramiko"
  - "pip install ansible"
# command to run tests
script: nosetests create_cluster.py
script: nosetests run_pi_yarn:test_create_cluster_run_pi
