language: python
python:
- '2.7'
env:
  global:
    secure: "YELLNiIaLsnIch5DFHgKk9ZFlWasujveMGc8qkIFrct1bis///wa0oa1BB8KGgPv4KWy8KUaBNZEv8L+DTRjHr2km1T5zf/G3OERQlrFrTqyunBaYazllDQTmqB7P+oDx3b4lTrHuD1vmdns9fJHqQaEnshA4VKSs5biox3avww="
install:
- pip install kamaki
- pip install paramiko
- pip install ansible
- pip install django
script:
- echo "decrypt public"
- for i in {0..10}; do eval $(printf "echo \$id_rsa_pub_%02d\n" $i) >> ~/.ssh/id_rsa_base64.pub;
  done
- base64 --decode ~/.ssh/id_rsa_base64.pub > ~/.ssh/id_rsa.pub
- chmod 600 ~/.ssh/id_rsa.pub
- head -1 ~/.ssh/id_rsa.pub
- echo -e "Host $master_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ls -la ~/.ssh/config
- head -1 ~/.ssh/config
- echo -e "Host $master_ip\n" >> .my_ip
- ls -la .my_ip
- head -1 .my_ip
- echo -e "$master_ip\n" > .master_ip
- ls -la .master_ip
- sed 's/Host //' .my_ip | head -1
- python legacy/run_pi_yarn.py --master_ip=`cat .master_ip` 2 100000
before_install:
- openssl aes-256-cbc -K $encrypted_908d3e898427_key -iv $encrypted_908d3e898427_iv
  -in .private/.kamakirc.enc -out .private/.kamakirc -d
