language: python
python:
- '2.7'
install:
- pip install kamaki
- pip install paramiko
- pip install ansible
- pip install django
script: nosetests create_yarn_cluster.py
before_install:
- openssl aes-256-cbc -K $encrypted_908d3e898427_key -iv $encrypted_908d3e898427_iv
  -in .kamakirc.enc -out .kamakirc -d
