language: python
python:
  - "2.7"
# decrypt private data
before_install:
  openssl aes-256-cbc -K $encrypted_58f4bd365cd0_key -iv $encrypted_58f4bd365cd0_iv -in .config.enc -out .config -d
# command to install dependencies
install:
  - "pip install kamaki"
  - "pip install paramiko"
  - "pip install ansible"
  - "pip install django"
  - "pip install mock"
  - "pip install rednose"
  - "pip install nose-cov"
# command to run tests
script: nosetests -sv
