language: python
python:
- '2.7'
env:
  global:
  - secure: "YELLNiIaLsnIch5DFHgKk9ZFlWasujveMGc8qkIFrct1bis///wa0oa1BB8KGgPv4KWy8KUaBNZEv8L+DTRjHr2km1T5zf/G3OERQlrFrTqyunBaYazllDQTmqB7P+oDx3b4lTrHuD1vmdns9fJHqQaEnshA4VKSs5biox3avww="
  - secure: "YDlXPTeVg3s8/TzbQ8YPyo5Rv9XGqgFPMJyWNJb6Vn6JdncMwiV5VJ9hbiTQC2VQ16CFDqPx174RX5WNYzEr/IvALSDO1KVzODlduQ9tL2xUwR/yGMDeCKgfPAPSf2WzzGY9Szh/nmTetpApp/jJnrzF7wQajOuHpAW86Op9PY4="
install:
- pip install kamaki
- pip install paramiko
- pip install ansible
- pip install django
script:
- ls -la ~/.ssh
- ssh-keygen -q -t rsa -P "" -f ~/.ssh/id_rsa
- scp ~/.ssh/id_rsa.pub -p $hpass hduser@$master_ip:/home/hduser/.ssh/new_key
- ssh -p $hpass hduser@$master_ip sh -c "'cat >> /home/hduser/.ssh/authorized_keys'" < /home/hduser/.ssh/new_key
- echo -e "Host $master_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "$master_ip\n" > .master_ip
- python legacy/run_pi_yarn.py --master_ip=`cat .master_ip` 2 100000
before_install:
- openssl aes-256-cbc -K $encrypted_908d3e898427_key -iv $encrypted_908d3e898427_iv
  -in .private/.kamakirc.enc -out .private/.kamakirc -d
