language: python
services: postgresql
python:
- '2.7'
env:
  global:
  - secure: YELLNiIaLsnIch5DFHgKk9ZFlWasujveMGc8qkIFrct1bis///wa0oa1BB8KGgPv4KWy8KUaBNZEv8L+DTRjHr2km1T5zf/G3OERQlrFrTqyunBaYazllDQTmqB7P+oDx3b4lTrHuD1vmdns9fJHqQaEnshA4VKSs5biox3avww=
  - secure: YDlXPTeVg3s8/TzbQ8YPyo5Rv9XGqgFPMJyWNJb6Vn6JdncMwiV5VJ9hbiTQC2VQ16CFDqPx174RX5WNYzEr/IvALSDO1KVzODlduQ9tL2xUwR/yGMDeCKgfPAPSf2WzzGY9Szh/nmTetpApp/jJnrzF7wQajOuHpAW86Op9PY4=
addons:
- postgresql: '9.1'
before_install:
- openssl aes-256-cbc -K $encrypted_72e235734e7a_key -iv $encrypted_72e235734e7a_iv
  -in .private/.config.txt.enc -out .private/.config.txt -d
install:
- pip install kamaki==0.13.1
- pip install paramiko
- pip install ansible==1.7.2
- pip install django
- pip install djorm-pgarray
- pip install psycopg2
- pip install djangorestframework
- pip install rest_framework_ember
- pip install selenium
- pip install mock
- pip install rednose
- pip install nose-cov
- pip install requests
- pip install django-celery
- sudo apt-get install sshpass
before_script:
- psql -c 'create user developer with createdb;' -U postgres
- psql -c 'create database escience with owner developer;' -U postgres
- python ember_django/manage.py syncdb --noinput
- cd orka-0.1.1
- python setup.py install
- cd ..
- npm install testem -g
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- nohup bash -c "webdriver-manager start 2>&1 &"
