language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install kamaki"
  - "pip install paramiko"
  - "pip install ansible"
  - "pip install django"
  - "pip install mock"
  - "pip install rednose"
  - "pip install nose-cov"
# command to run tests
script: nosetests -sv
