language: python
python:
- '2.7.3'
env:
  global:
  - secure: YELLNiIaLsnIch5DFHgKk9ZFlWasujveMGc8qkIFrct1bis///wa0oa1BB8KGgPv4KWy8KUaBNZEv8L+DTRjHr2km1T5zf/G3OERQlrFrTqyunBaYazllDQTmqB7P+oDx3b4lTrHuD1vmdns9fJHqQaEnshA4VKSs5biox3avww=
  - secure: YDlXPTeVg3s8/TzbQ8YPyo5Rv9XGqgFPMJyWNJb6Vn6JdncMwiV5VJ9hbiTQC2VQ16CFDqPx174RX5WNYzEr/IvALSDO1KVzODlduQ9tL2xUwR/yGMDeCKgfPAPSf2WzzGY9Szh/nmTetpApp/jJnrzF7wQajOuHpAW86Op9PY4=
before_install:
- openssl aes-256-cbc -K $encrypted_72e235734e7a_key -iv $encrypted_72e235734e7a_iv
  -in .private/.config.txt.enc -out .private/.config.txt -d
install:
- pip install kamaki==0.13rc3
- pip install paramiko
- pip install ansible==1.7.2
- pip install django
- pip install djorm-pgarray
- pip install psycopg2
- pip install djangorestframework
- pip install rest_framework_ember
- pip install selenium
- pip install mock
- pip install rednose
- pip install nose-cov
- sudo apt-get install sshpass postgresql-9.1
script:
- nosetests -sv tests/test_create_cluster.py
before_script:
- python -V
- npm install testem -g
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- nohup bash -c "webdriver-manager start 2>&1 &"
