language: python
services:
- postgresql
python:
- '2.7'
env:
  global:
  - secure: X6F9qYcVNhPYHSHF15WnTmOgR3GToC0DISFhCyTD0Lb3qsoxu4PuNWA3X6LazQ57U5we/7keZuwVJAhJzy3JiVUYPOIM6AnYmG/qqdmvuTwyzqqXR9E0ULBWPTtA4HKaz/3P3RjkAyQ3WjcD2dHbRaGA+cFvXoTRAzsUmWYBTx8=
addons:
- postgresql: "9.1"
before_install:
- export DJANGO_SETTINGS_MODULE=backend.settings
- openssl aes-256-cbc -K $encrypted_b254a382580f_key -iv $encrypted_b254a382580f_iv
  -in .private/.config.txt.enc -out .private/.config.txt -d
install:
- pip install kamaki==0.13.1
- pip install paramiko
- pip install ansible==1.7.2
- pip install django
- pip install djorm-pgarray
- pip install psycopg2
- pip install djangorestframework
- pip install rest_framework_ember
- pip install selenium
- pip install mock
- pip install rednose
- pip install nose-cov
- pip install requests
- pip install django-celery
- sudo apt-get install sshpass
before_script:
- psql -c 'create user developer with createdb;' -U postgres
- psql -c 'create database escience with owner developer;' -U postgres
- python ember_django/manage.py syncdb --noinput
- cd orka-0.1.1
- python setup.py install
- cd ..
- npm install testem -g
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- nohup bash -c "webdriver-manager start 2>&1 &"
script:
- nosetests -sv tests/test_create_cluster.py
