language: python
python:
- '2.7'
env:
  global:
  - secure: D29NF3NZ0Vg7JANyXNuxW5Eh4jz9mi/zKEbcIl2Nwe3KkTdCmshzQ2bONd57meb9wTqQbY8svCQ2GJwkdBDz6NMTbKD9QwE6+U5bT8ikTJ3isXd2sYiUp4ozpcvyFjNi+FS1yRGoGhWFlrIHiP1HyqQ7q3upiZUN3hOLjMLJckM=
  - secure: dkEazQurIr/JQkF/aBOaF0AC22PGuCyKTdFFRp/IVXRvU+e2Sg2nGsOjjkw1zckVpXj+xvZ5LNP2sFppFTEYbICcF1vMPhdbw5iaLFJLiqsqo4PuI8yNEvQbYXSLfO5pMX/uaeOrCY/zIOvag78E9NZv3kaPC4yeW97fEhJPHO8=
install:
- pip install kamaki==0.13rc3
- pip install paramiko
- pip install ansible==1.7.2
- pip install django
- pip install selenium
- pip install mock
- pip install rednose
- pip install nose-cov
- sudo apt-get install sshpass
script:
- ssh-keygen -q -t rsa -P "" -f ~/.ssh/id_rsa
- cp ~/.ssh/id_rsa.pub ~/.ssh/id_rsa.new
- sshpass -p $hpass scp -o StrictHostKeyChecking=no -q ~/.ssh/id_rsa.new hduser@$master_ip:/home/hduser/.ssh/
- sshpass -p $hpass ssh hduser@$master_ip "cat /home/hduser/.ssh/id_rsa.new >> /home/hduser/.ssh/authorized_keys"
- echo -e "Host $master_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#- nosetests -sv tests/test_create_cluster.py
- python legacy/run_pi_yarn.py --master_ip=$master_ip 2 100000
before_install:
- openssl aes-256-cbc -K $encrypted_8f68f3e32372_key -iv $encrypted_8f68f3e32372_iv
  -in .private/.config.txt.enc -out .private/.config.txt -d
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- nohup bash -c "webdriver-manager start 2>&1 &"
