language: python
python:
- '2.7'
env:
  global:
    secure: "BhCmy9ZL/rOWqE8mJTCIs+7IShWm29XTy23RWzy/49rgxnfC3YXQO4D9kJRD+zqpOI2ezfkxpwIJWeplEuGDuAmYWV2SaVUIZrWVYYtRHyxDBeufdJewURuvVeo0o7TK9zsAJOU5oPWn3VZ5Xjsa1bCqYL8ww/91ge1YWpUNwLc="
    secure: "C+HhwS/FIzoiJKDuWKOGpryIISMF8OQWIUm/o8cg1uq2gnvqeW3gX3oob2EJqUBsUdUE5VOSvNVu9f70q/E9ZKsIubXAz/wtKIrKEFqfaFF32FBC3u2kCZFf8sUNQxGn8nBkCibRr6YptAl3H65xCDevvGkH/LmY/Qrq6eKLvIg="
    secure: "hlZch9iW2V/764VB3Yp64uvUVIYP381J6L+YD+oBkkb2MWqCpmBwXdUOmS3FKwvJrtnUlomO05YxuefbFPeV9ceuqBKGwtAT+HQQOHUc21rpfFcFxdCv4GIvzFHNlYCfd8H7twFeYGei3pUG9wpTww+oohphgbw7YJpK2+8gPQg="
    secure: "Ln2I8EeMM6Oj0WZT46aNATQTzKQ5r9bk2b5XHgCTnJ7wPbg4TM9+m1yI15lEbJFFfBLjXs7JOfchP5AFBwv0b0IZKutaUTzwjG39joFH9u9YLKSFRFumNuYmHPQ25dPdwCz3Ba8RXJAQbpH8Rpl2SmZXNfSA+Rq/ufwjj6r/XYE="
    secure: "OAra8Qp9jSUEnhgqtgMGTCarPHNJDhFhShfacQJSPofTNpJGdWiSw8dvWJdg31NGx83Xpzp0AvODPU0Nj74o+sHAbE2NZLiq/Yd3J+ibnfRT5TSZFz6eeakVr8ox2fNiouyFqqfiolJXjlSss6K1S9WNzv8shUI4sNpMgk5mTy8="
    secure: "aPXodfAQHP1w4ivMAI0l3r2xDHjqog3iiBUOOcQseGb5dSiGLYTptpw2LCj618C637UXVfj3231kmMalkGIM9uKJxnZsxNjMLA3AUbedeSBVv9sAUKCGVRIOo4vnMHpaNkdDDDENnZYQfcoUDu3KCLNTaAH183dxrxZnwSD+HBY="
    secure: "e2srAourt0VDChC+whBqNbF5PW17SsFOJfGelfHxw0t8eSOdThvjOCjRZECz/YRQnz1Mn7YqlmHgszsewSobnem6GElvm8elBSF/wiNqU+dJHGYMdcaGGHq4kztapTZfLFnIRtZEO4bKWJA+I4QX6EwODaOpDyvcoJw2isJro9Q="
    secure: "hAvTF12WIEz3VyQk+r81DuOOwIAYepn3sw7jv5tVxXlW0xvk5DPsPSDmdyMA2jaULUAsao9p9nfq1b2NShlBePPL5HtzJbcwWak+DgPR/ARLCi9THyrbJrDCm3IpvSN+Vra15l46ujxyhVl9kiETBGwNln9xhJHL2hisZ2K9CcQ="
    secure: "c2F4pnOvsqz6gBDDWLlheelHU4ZdRbMMHw4y9+5OoveH/f1W8zkxQeuzjcB0a8SZJFSC1/GNMgbElmm/rxk44+LR9IxxF6zYa4VI0P73Iii/tEHCqHIIyUtKUMp/6S3HT4/G5E26EoR2YcVwYUqAHjEWkI04d3fjXIwc3SoupLM="
    secure: "YxIBhVfgidt04ZJoV3I71FrDIbq+M1ekXFKz1qiZGdPicwVbvNvgisaHahvY1qTf1sfXcnup8teRJkcAAys80lXRSUuK3a4dqLdUq5HeC9MsDf+iATlSPj1sFsQxqa+69Frq9c1flGnhkQyr9RNY8neA7TsUFm3axbBUFepWwU8="
    secure: "jwk1eQDTEq2M9BfgpAUMCb6UnlmMtLMBkb33wP/LdUjuvYmJ6FxwWprLxvTSjXpc9lC+M/Vv+/n9KkUzmBWcUMVTWYBWYinWvvSs6BhOSDELLl4e+5fyKsTQvHGqzszwRmWZHGNTLXU6/MCzZ9kWRtVjBMObtUEztu83RcUQesw="
    secure: "lGsMP+88pYArQZmz1/nfiVRgufxX19TDbC7ZwcJjOOQgfvU93lDHgkzW4n5lh2PqQ39AU1W/2oVuqqD36F4HN1kqekyeFc6IG+b50aJ0PDPAV5+l6AM9drQkdUNT16FLMPJWWrjYvVCC9K1OF/NEuONEGFrLRoE7FUgMI7HpsMc="
    secure: "L5nHZjDPFfE3wlMeQ6XSplUdLJgEt0O65QZ8kg08XSxj9+O6xtc28wYUtWvFMZuGJupS+EOQYlyOISkkyOysMEzaHBAIqo0pQTrjgOCXWy0qth++jFnujYXwsi4fTtCLHK3iQIChrctct5h41zh9/lA1kD3t60d0xe2GV7yCj/c="
    secure: "Z8xHT+VHRV+fQtJBgT5U29iyEm2TcKzO6SoIAUUk532ECyKihDhAw0F3JvmKPyqK15ozIAW4hLqhCkRYSu2nfEXdDtZvD7qtVpUnFmw3le2sbGiu+l78lSJd7rKV7PjsEDvCsjSUL34ZEndkRugh0KMpXnq6CuI5ZzfTDbVEU6M="
    secure: "MbrgOBHbmPZiSl/0eQUoIWQoB0WDa0ToXdILe84iZ3DjEaX1KAE3omCiZ0Fp7JT3pO0Ru+hrwPL8/7Z8kEtHJV68tpZE53R+FwCpUV2O1iEqaMlGw556awYvg6+4PRMmapt2imDx+i3A8uG3yLAJAmkkOj5qW1TeYhIy+T+t4G8="
    secure: "cxCYwsAu189sBoVMgk4AyOPNs21nfRvMUfU99agAPZ0oSeQk9vC/lu6ATKuND/9HQafYWkTnPRFfwWv6bTru3qzqDzaDJ7OZ7OKtKHiW53ADCrq/FU8g/fwciE9helNS/qyDmqZ1FMIPgYMZ6yncWAP/tEiEe+xPQZjZWa1kK8s="
    secure: "hN7BXJeyqKOKsefis1x+W0JAJJYG/gkBjOQSloJ52+LbeBMFvTE0Hgc6rFz/Co3Vk6pSbg+5iZ47n7/iLDihzJsMmgU2utG9/lsxWTIJOfpoB7Bqm8EtKGuHnmmMdFMb5mQxkfVQMw/TW1mvbJmGslx6InBtQbKcz61y+LO1RzI="
    secure: "Br0dM2lApZvPDv3ues2kNvlw0fbNozpssxzOuA5i74S7ZS4DeLf+dnY9cnWp+QU65dl4RVNnytkCrAOW1FVyDtbLzcSKxRqca39TnPiTJvKnPkjySnY/2qJIJvlFbT3YyaOe5LNa6S3gmW0hisxXKRJDr8qQ3mSFtgAFEX0HLB8="
    secure: "Cw8DZLhIvcHWPr/BWlKJEOMS3QyE3GYp9cylYOXd50j1vm7IlLQcT45bmgWM8k94aS5cGqEeNfRVkRobe7oD/N8wQufdePDclhkj9NPAuAS++e92k860poCtbqLIYYiFIeW0SokPxkfzj2iyM1Gy70F1eequrt1JwQZ1/bNAqHU="
    secure: "P8HWqYypNIz/ltvqA7NkawKNaRLSE8nl8rqgx38XwGWc27OyxB9g1NDIdUgXTUs/okxCQOsFLSA7HaMF2cjv7upk7tpFMF6KMsMl34EE8Pe2/itSvZXzc0XMUNMGqBAyn4DNwe4Xzps2bGOdz7x/5LOrTkTwC1DqC8/7BQqi05Y="
    secure: "FER9tYR7jkdRuad7CCQKI+s9gfmw33feHW5A01/aidkuafJLiFkO0QOuJjPiApd/NBgJEVHZDFs3IUywZxKJoLUtMXSfJrALky7yx49xJj6POxVPmSScX7NrgKdykeG52EKkSApqfuF74UPX+YjMsP/VYkgg84NUODQwU/NHTIE="
    secure: "TRbsVW94IJEuBpSjVr69h28FgiOMB9pxurllk9RlDcw5YBT5T3P4fjAQfpIIBTSvI8KZyM99ES3MM/OtfYVEFDYa1MJ8yqcpgPM3u3LQL32xgPBXoUJeB/7YEuRubW7fQ5UCMgd/kvdqz0rRkzrLIfs+J8Vn2FON5ccc//hy40c="
    secure: "NTzKhhAwbcCq6age6GTrBUxSvxWkNL8abnkp3RnFe7wPawBCVb8t369FRoS3HBVJHCmEtuX1tseSMOIHFg1Nj+yWUj7poLF/wSRFSIYnJwZj1p1BvHafbnm6wvtDC0/5P4Mpyy9a69mRYBoIoy7AMbZdgA9zAyxfoJve+FWNF8g="
    secure: "JEQ39tyCPV+2vkz7dU9forDaNnJz1yq4OPRwsBMtnd9IY5yOFwLS/Va0xkqpKK9W+RWla1Kx3ec8muAQXrhlp0WdmpzmDTMEFT+T4J7HigttCvSGCP9Nrh4yvSpss3m4IbDGUOfQmCltQ7uvdFV2W3NCkwT4IQx13uBQXr0lo88="
install:
- pip install kamaki
- pip install paramiko
- pip install ansible
- pip install django
script:
- echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $master_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "$master_ip" >> .private/.master_ip
- head -1 ~/.ssh/id_rsa_base64
- cd legacy; python run_pi_yarn.py `cat .private/.master_ip` 2 100000
before_install:
- openssl aes-256-cbc -K $encrypted_908d3e898427_key -iv $encrypted_908d3e898427_iv
  -in .private/.kamakirc.enc -out .private/.kamakirc -d

