language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install kamaki"
  - "pip install paramiko"
  - "pip install ansible"
  - "pip install django"
# command to run tests
nosetests create_yarn_cluster.py
