language: python
python:
- '2.7'
install:
- pip install kamaki
- pip install paramiko
- pip install ansible
- pip install django
script:
- echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
- base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host $master_ip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -n $master_ip
- head -1 ~/.ssh/id_rsa_base64
- cd legacy; python run_pi_yarn.py $master_ip 2 100000
before_install:
- openssl aes-256-cbc -K $encrypted_908d3e898427_key -iv $encrypted_908d3e898427_iv
  -in .private/.kamakirc.enc -out .private/.kamakirc -d
env:
  global:
    secure: Y4A7+EJMHDdl7PR9CiNshOKXgU+7cN9hzO8JA8ue0kTBzJ5xDjonBPLsQ7j9811NOH8oyvduPpg2MoVbNoX3bbwdkMWzJ4HP8vjKeBiuA4Xuj5C8kyN+uL8WfDzFzk+D1kabDrIPS9ll34IzXkIgOP+G9MiYuv8kKal1tRCkq9M=
    secure: "IrKd3UbnCvej+MnfuQfHr42h4agTGm51LBl2hZhI2gNyS81oaxQzTEbsmZOZj3zqpByTmFJlQYp+KeFsOv+kyjhjA4y/taZXfcqlXpictlhB/TUJmHdskJRJyErL+GbmRQqqaVKUM+ZRDFV3AxayegOLfW4zXw0YzsVMDnRmQeE="
    secure: "PWOk+dCsZZpArB9VyqoN/FOvMmc8Adcxys5lPLbNnWofbuW45FgkXkv+iR1szOAyBIj0t0/QL4VW6MtWUY+jychMSPAuA3HXYxdsxotF+Zg2V4FF8EjF+m4EFcm2m+t44n5cnv/eAnwEk+xo6+0E9jhroI2WnsiWXhdKeImw/44="
    secure: "DS11d0jEar5fvKPzofCpM0UQCX1YhjY+TT9uDuDmhHlbDsuiKm7j0Wx+PhYZRI0AhlvUC4YCt0IGZVHz+8YZ0WHiG6oYed/4VQWT+57CVdzQ0U7sEHB7PrJ/tazTqHjc0hZZWNFD+xWLDlg9nSmMqdmui6P21WPJj2orqxbFz+o="
    secure: "FgYT9E5PnHto6hBEXB3XVB87aT+8h0ZxJpnANjy9WiwRc6wX3/mUzIIexfOac1KskzusVlBiT2KPJhIn4gnfdybVaojIG78xLISpj/Pwt4KviBvTt4IFBHpnzmgizHaw5er4YRYHQBOe0aMKzmAYpkVRHQPNsWMKcenT+jokY/M="
    secure: "MKvX+P1pHP721GFNUQ+NrvmQqWNpKC64iftOIcCihep5dt4HvErr7I5hQQmM9bvM5/HFq3KLZiZdmySiTmmW01IhWfpk85ExhumErAAHFPGRuQFrH15kZ6Ak+w980ml9XibFrNqI6S6cN5p/Q+l3+N235Cv+URuPPxx3OuxI9gU="
    secure: "AbmlhupYyKzoY7kinw0XWfMOUhPEtIhS8AcX28ViEK/6pTPXwlsV7KsAquF+Or/xz1x6JruBSxz3vQUmpp4snAydAzS8R9SJgryThP5CHpkaXTKKX8Gbohy7rAUwwSaMx2zaLMZk0MCyniRQsbC39aOoggYY+YNS/0cuLa4rlsA="
    secure: "YajQNypFhM5ohFePdjASrdIkjZmjOCsyLzjhQw61y46IG/ql+6dvgJqt9481TGb7OihqOxlYJ7W6U12Tgxl7cPUP76alEoak/GHzDvdlSYi8k7NqdsYesType00+P7YjGSkyg7ztEOXIA2IW/6avIfjUxtgdwcLvgvVZbJEmULA="
    secure: "F62S8OxHc3+O4pRzJjOFHrBl3wmxpmVekRGr1wWElCWQLpuUwdYxAaiIqiZ/2ex0/MVZ+KY1hyzM8j7eUXko+Et0L75/WcG/MA+WVR95In0nbUbVhRrvf9qi6n4h0g7BH55ZxBBnX6Wih/9neMFmgN6tOb6anP/UER0nTucpL7c="
    secure: "XdQ5A8lLxBfYoXVZh/boyvt+mBA+zm8EK/gYZpqAVjPp/eXtHZIP43tSaE0Sfom69H4DAyxKm2AzoEPvZuQHVxBXAOy8o1/ghULh9DG7c1espkC+NMmAoFHviXUvlTk/X2evF5CkyUhvSdrpnHfuE3nQyRZ56TX0sg7ZHxj0yGg="
    secure: "OnO8Enl24Zw1F2aWxpylWvZJrVVIat9KK3lzN0cWf6+t3O1l4gTuKNPhAnRQwP8L3efmceFTjFJ3WX9uKYXgSs5XT2SZYAaxkgVLk8Ux4acrcfY1ty6vB5J5Z2aEmrg9yUKsKe2XjaNRbXzY8uXhmzobhtijXGrVcEBTTMl7z1c="
    secure: "JIbJfcJSXsCOFMaOb3R9mMN4BnOze0gGXGcHqXFmhKwNOk8py+4Nis2NbNmaEsqRmCTst6MnUbdeDL6TDw5tt1Y10+hZmFV+0zi5uhMpykbUTaAPMVnkaZuNH8oktvVEtdAPov1a8QD0gsK3Ygufd7761RiBIIaI61adzzo/ecM="
    secure: "ZX7CNcJc5F7uu3PJqajv27Hyf3AptV7mNftlYfr2KVC572K2kBBsfgow0nThvDTeLJTWrSDqREoMYkCrx1eWgFBzy0EuBPnm2CzaaNZ7aSfEChPL3alYxTZ/gxz8/BzyixAfTaAIPyQm0MexlPZaiJqNrey0FVI99IFKhgDQ9gY="
    secure: "WEAFh9JV++vOl+yaXO83GvQmRDGGigCHR+4hiWx7jl2AMhi0U4sXmEGoX5nDVdSKKLbFwpgOlCpVSRFJ7XVu9GbfDP8exi4LlYXbjeyj8EDyx2FKLaXvv1GYV2KnFjUNgu9A2ZNPtr2p74FSK+cOnynwOB56LQ5ksvbEQqqQdtw="
    secure: "SG2Rnj7/POpRguVXZwRjRCCQdd1XEFOvUXRcGOmTPqHcOS98sn8sW83DT5XHJV9kR6f/N3QXuOqCVU2GeBroC4R4VKSNkj0dTtVUyCAVi7onq6wrUOOMtxj76EFXp9IJOu+Us+qnSMZJ3bL912z++DJ8IfmoxiTFb9TTlQReP7E="
    secure: "BLLL+yl3ko6Bx/x2o/u7LrKae41IFXPxq+cMjADMRabJsndBiosRs6DV7nwfiO7MBGZkGjjBfu7BLCEalxSry3EJlNqXmZzmC8ApTajSsGXdHq4DJu9PyJZXGtzQjIpID4u+nFux2ReBWNXimgM/IlVOIEXkTkEkpYvRdq5VCFk="
    secure: "f/hpqfEcgSmiPhykVDcAedZUCeMRvlpxsuFeBXb9nYxxi7qaOdeL4PGXkRmTrQTqamPjXelS7NJbablBJ7ZQ+Z3UoRLm1kYLk5QSmxNTwjsEJSwFrcVW/tl5e/a3wW74ecdkyHlxc7FkbwpeNe9RmRcxXnB01xlaJxAxquAa0U4="
    secure: "f97DCSUkAxD/7RlT3Y8ECVU+pY6oeYqbFOKW6IFSmm45NOT0Dt90Q653GX0jWJUK10ZUyf02+QRQskd6V+fMAFNA2WxbSf5DqPcZh2nH1pTJ5Nim0HlfC+348gXXemGDAf/RrL76sUJR6LKpWZfaNISxPgNQSeqzMAbBE3C20pE="
    secure: "RwlYpVIdwNShTgga8zg91vhm7OMr/6t60sU2zNHukKvKLz2ylH/+jd/U/t8QVOG8Q3KfkOfdF+LNSeKW/AKZmQIxafFh5n/W5A6gsvksi3pB8xaBtdQ4lUWohtrEhn3zZ17kPQJsjBiQLpHModwZkaTgrp/2FR1nSljyYHmWOw8="
    secure: "i0Iku9RSLBMwDobPsKqMZWsofHqlDTwUM7kXkVyMwU5g7aScVlSZfYJRuDuhupLyIHDCl4ly7AsItzRqlfmwc+e0d1UG7pR0vh56x5ho2H2OMAZ4fkq8NiBV9TXMxHf6n2oXY0AaxR+utzL6wPPNk16634NExrE4PeVa7N3RZbA="
    secure: "V7PBHNODCiSUFV94b6Ybk5fzVj3DTWTDBk93INXT+OZ1r/m3585Cglz6TEUT4bdKRj4Toa7RZM9vRXmB/eyoNme0+HN6Qx4c7TpIoyvHQ/ajgdQKXqDQwKppErQPCuleiSlWXLPTqYObKQG3ARtRVwB1HspclWNaw1OTOnxObKs="
    secure: "SYpd6QBwcjOLUjGC/LS3pmx3bBFb1n0PcCxgNluwsb0wsR1DSFR0CPRJmNUxJZrlDuUnE7FzigH7G0OSUpEuUsKRCQPqxdWtn69q3xzUhwkQ7yg6tFh8+XDh5yG2qiPVNBkHRV3mtPexyt3bm2OdSHtX5BuVK+slGZ6eEoSNS1I="
    secure: "Ab790Y73p7PJApqrK/Dmb2iKyXCwSqjYPU6hFon/L6A1FS8dDYG0kVx8Plt3QYYe3kyVOqM2T89HBzeri9/cI0HQgts1Vrk3Sx7q7ApoxGmIQEQz1DPYJ5yDXp4jN61+ziYDD1ISErbnvI7iMxesnk4dfRbTi66pJkxf9v4eHxc="  
