-
  hosts: all
  user: root
  tasks:

  - name: Update and Upgrade
    apt: state=latest upgrade=yes update_cache=yes

  - name: Install PostgreSql
    shell: LC_ALL="C" apt-get -y install postgresql postgresql-client
