---
- name: Setting up common tasks for every host 
  hosts: all
  user: root
  roles:
     - commons

- name: Installing and configuring Hadoop-yarn cluster
  user: root
  hosts: 
    - master
    - slaves
  roles:
    - {role: yarn, is_master: True, when: "ansible_hostname == '{{ hostvars[groups['master'][0]].inventory_hostname_short}}' and choose_role == 'yarn'"}
    - {role: yarn, is_slave: True, when: "ansible_hostname != '{{ hostvars[groups['master'][0]].inventory_hostname_short}}' and choose_role == 'yarn'"}

- name: Format cluster (if needed) and start the Hadoop-yarn daemons
  user: root
  hosts: master
  tasks:
     - { include: start_yarn.yml, when: start_yarn == 'True'}

- name: Setup orca_admin user in Django server
  hosts: webserver
  user: root
  tasks:
     - { include: setup_orca_admin.yml, when: create_orca_admin == 'True' and choose_role == 'webserver'}

- name: Installing and configuring Django server
  hosts: webserver
  user: orca_admin
  sudo: yes
  roles:
     - {role: webserver, when: choose_role == 'webserver'}
