---  
  - name: Update and Upgrade
    apt: state=latest upgrade=yes update_cache=yes
    
  - name: Configure locales problem
    tags: localeconf
    locale_gen: name=en_GB.UTF-8 state=present
    
  - name: Install Sudo
    tags: sudoinstall
    apt: name=sudo force=yes
