---
- hosts: gruntserver
  user: developer
  sudo: yes
  vars:
    project_path: path
      
  tasks:
  - name: Install curl
    tags: install_curl
    shell: apt-get -y remove apt-listchanges && apt-get -y install curl

  - name: Download NVM
    tags: download_nvm
    shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.12.1/install.sh | bash

  - name: NMV Commands in Terminal
    tags: nvm_commands
    shell: bash -lc "source ~/.profile" 

  - name: Install NVM
    tags: nvm_install
    shell: bash -lc "nvm install v0.11.13"

  - name: NVM default version
    tags: nvm_default
    shell: bash -lc "nvm alias default v0.11.13"

  - name: Install grunt-cli
    tags: grunt-cli_install
    shell: bash -lc "npm install -g grunt-cli"

  - name: Install and add Grunt
    tags: grunt_install_add
    shell: bash -lc "npm install grunt --save-dev"

  - name: Install and add uglify
    tags: uglify_install_add
    shell: bash -lc "npm install grunt-contrib-uglify --save-dev"
    
  - name: Run grunt tasks (uglify)
    tags: grunt_tasks_run
    shell: cd {{project_path}}; bash -lc "grunt default"
    