---
  - name: Install pip
    tags: installpip
    shell: apt-get -y install python-pip
   
  - name: Install passlib
    pip: name=passlib
    tags: installpasslib

  - name: create django group
    group: name=djgroup state=present
    tags: djgroup

  - name: create django user
    user: name=djuser group=djgroup generate_ssh_key=yes shell=/bin/bash update_password=always password={{djuser_password}} state=present
    tags: djuser

  - name: Add djuser to sudo group 
    shell: usermod -a -G sudo djuser
    tags: addsudo  
   
  - name: copy local box master ssh key to djuser
    tags: sshdjuser
    authorized_key: user=djuser key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
