---
- name: Setting up common tasks for every host 
  hosts: all
  user: root
  roles:
     - commons

- name: Installing and configuring webserver
  hosts: webserver
  user: root
  roles:
     - {role: webserver, when: choose_role == 'webserver' or choose_role == 'all'}

- name: Installing and configuring {{hadoop_version}} on master node
  user: root
  hosts: master
  roles:
     - {role: hadoop, is_master: True, when: choose_role == 'hadoop' or choose_role == 'all'}

- name: Installing and configuring {{hadoop_version}} on slave nodes
  user: root
  hosts: slaves
  roles:
     - {role: hadoop, is_slave: True, when: choose_role == 'hadoop' or choose_role == 'all'}

- name: Installing and configuring {{yarn_version}} on master node
  user: root
  hosts: master
  roles:
     - {role: yarn, is_master: True, when: choose_role == 'yarn' or choose_role == 'all'}

- name: Installing and configuring {{yarn_version}} on slave nodes
  user: root
  hosts: slaves
  roles:
     - {role: yarn, is_slave: True, when: choose_role == 'yarn' or choose_role == 'all'}
