---
    - name: Create the exclude file with the hosts to be removed
      tags: remove_yarn_nodes
      shell: echo {{hostname}} >> /usr/local/hadoop/etc/hadoop/exclude

    - name: Change owner of exclude file
      tags: remove_yarn_nodes
      shell: chown hduser:hadoop /usr/local/hadoop/etc/hadoop/exclude

    - name: Remove decommissioned slave from hadoop slaves file
      tags: remove_yarn_nodes
      lineinfile: dest=/usr/local/hadoop/etc/hadoop/slaves regexp={{hostname}} state=absent

    - name: Refresh datanodes
      tags: remove_yarn_nodes (refresh)
      remote_user: hduser
      command: /usr/local/hadoop/bin/hadoop dfsadmin -refreshNodes

    - name: Refresh datanodes
      tags: remove_yarn_nodes (refresh)
      remote_user: hduser
      command: /usr/local/hadoop/bin/yarn  rmadmin -refreshNodes