-
  hosts: all
  user: root
  tasks:

  - name: Install Python
    tags: pythoninstall
    apt: name=python state=latest

  - name: Install Pip
    tags: pipinstall
    apt: name=python-pip state=latest

  - name: Install Django
    tags: djangoinstall
    shell: pip install Django
