---
  - name: format hdfs
    tags: format
    command: sudo -u hduser ./hdfs namenode -format -force chdir={{hadoop_home}}/bin

  - name: start dfs
    tags: start
    command: sudo -u hduser ./start-dfs.sh chdir={{hadoop_home}}/sbin

  - name: start yarn
    tags: start
    command: sudo -u hduser ./start-yarn.sh chdir={{hadoop_home}}/sbin

  - name: start history server
    tags: start
    command: sudo -u hduser ./mr-jobhistory-daemon.sh start historyserver chdir={{hadoop_home}}/sbin

  - name: Creates directory
    tags: HDFSMkdir
    action: command {{item}} chdir={{hadoop_home}}/bin
    with_items:
      - sudo -u hduser ./hadoop fs -mkdir /user 
      - sudo -u hduser ./hadoop fs -mkdir /user/hduser

  - name: Stop dfs
    tags: stop
    command: sudo -u hduser ./stop-dfs.sh chdir={{hadoop_home}}/sbin

  - name: Stop yarn
    tags: stop
    command: sudo -u hduser ./stop-yarn.sh chdir={{hadoop_home}}/sbin

  - name: Stop history server
    tags: stop
    command: sudo -u hduser ./mr-jobhistory-daemon.sh stop historyserver chdir={{hadoop_home}}/sbin