---
  - name: format hdfs
    tags: format
    command: sudo -u hduser ./hdfs namenode -format chdir={{hadoop_home}}/bin

  - name: start dfs
    tags: start
    command: sudo -u hduser ./start-dfs.sh chdir={{hadoop_home}}/sbin

  - name: start history server
    tags: start
    command: sudo -u hduser ./mr-jobhistory-daemon.sh start historyserver chdir={{hadoop_home}}/sbin

  - name: start yarn
    tags: start
    command: sudo -u hduser ./start-yarn.sh chdir={{hadoop_home}}/sbin
